[tools]
hk = "latest"
java = "21"
ninja = "latest"
node = "lts"
"npm:ktfmt" = "latest"
pipx = "latest"
"pipx:clang-format" = "latest"
pre-commit = "latest"
prettier = "latest"
python = "latest"
"vfox:cmake" = "latest"
xcodes = { version = "latest", os = ["macos"] }
swift = { version = "latest", os = ["linux", "windows", "other"] }
pkl = "latest"
actionlint = "latest"
shellcheck = "latest"

[settings]
lockfile = true
experimental = true

[hooks]
postinstall = [
  "hk install",
  # Install and select XCode from .xcode-version
  "xcodes install",
  "xcodes select",
]

[tasks.check]
description = "Run hk checks."
run = "hk check --all"

[tasks.fix]
description = "Run hk fixes."
run = "hk fix --all"
