[versions]
# Regular libraries: keep as up to date as possible.
accompanistPermissions = "0.37.3"
alchemist = "0.2.0"
androidx-activity = "1.11.0"
bytesize = "2.0.0"
htmlConverterCompose = "1.1.0"
kermit = "2.0.8"
kotlin-wrappers = "2025.10.9"
kotlinx-coroutines = "1.10.2"
ktor = "3.3.1"
lifecycleRuntimeCompose = "2.9.5"
maplibre-android-sdk = "12.0.1"
maplibre-android-plugins = "3.0.2"
maplibre-js = "4.7.1"              # TODO: is outdated; update to v5.x
playServices-location = "21.3.0"
spatialk = "0.6.1"

# Regular tools: keep as up to date as possible
gradle-dokka = "2.1.0"
gradle-jgitver = "0.10.0-rc03"
gradle-mavenPublish = "0.34.0"
gradle-mkdocs = "4.0.1"
gradle-spmForKmp = "1.0.3"
gradle-ksp = "2.3.0"
simplejni = "3.14"

# Libraries coupled to Compose: keep Compose up to date and set others accordingly.
# https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-compatibility-and-versioning.html#jetpack-compose-artifacts-used
gradle-compose = "1.9.2"
androidx-compose = "1.9.4"
jetbrains-navigation = "2.9.1"

# Android and Kotlin: Keep Kotlin up to date and set Android accordingly.
# Also note the Gradle and XCode versions in the matrix!
# https://www.jetbrains.com/help/kotlin-multiplatform-dev/multiplatform-compatibility-guide.html
gradle-kotlin = "2.2.21"
gradle-android = "8.11.1"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
alchemist = { module = "io.github.kevincianfarini.alchemist:alchemist", version.ref = "alchemist" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-composeUi-testManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-compose" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "jetbrains-navigation" }
bytesize = { module = "me.saket.bytesize:bytesize", version.ref = "bytesize" }
htmlConverterCompose = { module = "be.digitalia.compose.htmlconverter:htmlconverter", version.ref = "htmlConverterCompose" }
kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }
kotlin-wrappers-js = { group = "org.jetbrains.kotlin-wrappers", name = "kotlin-js", version.ref = "kotlin-wrappers" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-playServices = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
maplibre-android = { module = "org.maplibre.gl:android-sdk", version.ref = "maplibre-android-sdk" }
maplibre-androidOpenGL = { module = "org.maplibre.gl:android-sdk-opengl", version.ref = "maplibre-android-sdk" }
maplibre-androidVulkan = { module = "org.maplibre.gl:android-sdk-vulkan", version.ref = "maplibre-android-sdk" }
maplibre-androidDebug = { module = "org.maplibre.gl:android-sdk-debug", version.ref = "maplibre-android-sdk" }
maplibre-android-scalebar = { module = "org.maplibre.gl:android-plugin-scalebar-v9", version.ref = "maplibre-android-plugins" }
playServices-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServices-location" }
simplejni-annotations = { module = "io.github.gershnik:smjni-jnigen-annotations", version.ref = "simplejni" }
simplejni-kprocessor = { module = "io.github.gershnik:smjni-jnigen-kprocessor", version.ref = "simplejni" }
spatialk-geojson = { group = "org.maplibre.spatialk", name = "geojson", version.ref = "spatialk" }

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle-android" }
android-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "gradle-android" }
android-lint = { id = "com.android.lint", version.ref = "gradle-android" }
compose = { id = "org.jetbrains.compose", version.ref = "gradle-compose" }
dokka = { id = "org.jetbrains.dokka", version.ref = "gradle-dokka" }
jgitver = { id = "fr.brouillard.oss.gradle.jgitver", version.ref = "gradle-jgitver" }
kotlin-composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "gradle-kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "gradle-kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "gradle-kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "gradle-ksp" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "gradle-mavenPublish" }
mkdocs = { id = "ru.vyarus.mkdocs-build", version.ref = "gradle-mkdocs" }
spmForKmp = { id = "io.github.frankois944.spmForKmp", version.ref = "gradle-spmForKmp" }
